CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY USING INDEX TABLESPACE vals_index_space,
    email VARCHAR(42) UNIQUE USING INDEX TABLESPACE vals_index_space,
    phone VARCHAR(22) UNIQUE USING INDEX TABLESPACE vals_index_space,
    hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) UNIQUE NOT NULL
)
TABLESPACE vals_db_space;
