[package]
name = "secure"
version = "0.1.0"
authors = ["Alex Sarapulov <1molyee@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
rand = "*"
rand_core = "*"
scrypt = { version = "*", default_features = false }
