[package]
name = "api"
version = "0.1.0"
authors = ["Alex Sarapulov <1molyee@gmail.com>"]
edition = "2018"
publish = false
readme = "README.md"

[dependencies]
core = { path = "../core" }
data = { path = "../data" }
toml = "*"
serde = "*"
serde_derive = "*"
